server:  
  port: ${PORT:2222}

# Used by actuator and togglz
management.server.port: 2221
  
spring:  
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 4
      
#spring:
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false

#ribbon:
#  eureka:
#    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
app.api-desc: Account API

togglz:
  console:
      enabled: true
      path: /togglz-console
      secured: false
      use-management-port: true

  endpoint:
      id: togglz
      enabled: true
      sensitive: true